name: Sandbox to play GHActions in :)

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check Java version
        run: java --version
        
      - name: Check Maven version
        run: mvn --version

      - name: Setup and Java 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Check Java version
        run: java --version 

      
